default: &default
  adapter: mysql2
  # encoding: unicode
  host: mysqlinstance.c0mbfmyufmzf.us-west-2.rds.amazonaws.com
  port: 3306
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vensera_development
  username: vensera
  password: 15563200025ff0

test:
  <<: *default
  database: vensera_test
  username: vensera
  password: 15563200025ff0

production:
  <<: *default
  database: vensera_production
  username: vensera
  password: 15563200025ff0
